dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: jxdemo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: react
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
